package com.example.alarm86.infrastrucrure

val DAY_OF_WEEK_SERVICE_KEY = "DAY_OF_WEEK_SERVICE_KEY"
val ALARM_SERVICE_TAG = "ALARM_SERVICE_TAG"
val ALARM_BROADCAST_RECEIVER_TAG = "ALARM_BROADCAST_RECEIVER_TAG"
val VIEWMODEL_TAG = "VIEWMODEL_TAG"
val NOTIFICATION_CHANNEL_ID = "NOTIFICATION_CHANNEL_ID"
val START_ACTIVITY_WITH_ALARM_ACTION = "START_ACTIVITY_WITH_ALARM"
val SETTING_ALARM_REQUEST_CODE = 68
val FOREGROUND_SERVICE_ID = 2